version: '3.8'

services:
  # Application
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: movies-hub-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    restart: unless-stopped
    networks:
      - movies-network

  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: movies-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - movies-network

  # Redis for Caching
  redis:
    image: redis:7
    container_name: movies-cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - movies-network

networks:
  movies-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: